# Generated by Django 4.0.3 on 2022-03-10 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('apartment', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('zipCode', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tenant_mgmt.address')),
                ('ownerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_property_set', to=settings.AUTH_USER_MODEL)),
                ('tenants', models.ManyToManyField(related_name='tenant_property_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('CRE', 'Created'), ('ASS', 'Assiged'), ('PRO', 'Progress'), ('COM', 'Complated'), ('DEL', 'Deleted'), ('CLO', 'Closed')], default='CRE', max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_issues_set', to=settings.AUTH_USER_MODEL)),
                ('assigner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_issues_set', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant_mgmt.issuecategory')),
                ('related_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_mgmt.property')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_issues_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.TextField(max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('authorId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issueId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant_mgmt.issue')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
