# Generated by Django 4.0.3 on 2022-03-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_mgmt', '0002_property_dateadded_alter_address_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='ownerId',
            new_name='ownder',
        ),
    ]
