# Generated by Django 4.0.3 on 2022-03-10 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_mgmt', '0004_rename_ownder_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_properties_set', to='tenant_mgmt.address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_property_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
