# Generated by Django 4.0.3 on 2022-03-10 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_mgmt', '0005_alter_property_address_alter_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='tenants',
            field=models.ManyToManyField(blank=True, related_name='tenant_property_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
