# Generated by Django 4.0.3 on 2022-03-13 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_mgmt', '0006_alter_property_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
