# Generated by Django 4.0.3 on 2022-03-13 22:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_mgmt', '0009_issuecategory_dateadded_alter_issue_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-dateUpdated', '-dateAdded']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='authorId',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='created',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='issueId',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='updated',
        ),
        migrations.AddField(
            model_name='comments',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='dateUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='issue',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='issue_comments', to='tenant_mgmt.issue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='messageText',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Cre'), ('ASSIGNED', 'Ass'), ('IN_PROGRESS', 'Pro'), ('COMPLETED', 'Com'), ('DELETED', 'Del'), ('CLOSE', 'Clo')], default='CREATED', max_length=20),
        ),
    ]
