# Generated by Django 4.0.3 on 2022-03-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_mgmt', '0013_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Cre'), ('ASSIGNED', 'Ass'), ('IN_PROGRESS', 'Pro'), ('COMPLETED', 'Com'), ('DELETED', 'Del'), ('CLOSED', 'Clo')], default='CREATED', max_length=20),
        ),
    ]
